---
tbl-cap-location: top
reference-location: document
---

# Quel modèle choisir ? {#sec-choix-modele}

La tableau synthétique ci-dessous permet d'identifier rapidement quelle fonction utiliser en fonction du type de variable à expliquer, du type de distribution et de la famille de modèles (modèle de base, modèle avec prise en compte du plan d'échantillonnage, modèle mixte ou modèle GEE).

::: {.content-visible unless-format="pdf"}
::: {.column-screen-inset-right style="text-size: .8em;"}
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
| Variable à expliquer                         | Type de distribution               | Interprétation des coefficients | Modèle de base                      | Échantillonnage complexe            | Modèle mixte                                              | GEE[^choix-modele-1]                |
+:=============================================+:===================================+:================================+:====================================+:====================================+:==========================================================+:====================================+
| **Continue**                                 | Linéaire                           | directe                         | `stats::lm()`                       |                                     | `lme4::lmer()`                                            |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | Gaussien                           | directe                         | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
|                                              |                                    |                                 | avec `family = gaussian`            | avec `family = gaussian`            | avec `family = gaussian`                                  | avec `family = gaussian`            |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
| **Comptage\                                  | Poisson                            | RR\                             | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
| **(nombre d'occurences)                      |                                    | (risques relatifs)              | avec `family = poisson`             | avec `family = poisson`             | avec `family = poisson`                                   | avec `family = poisson`             |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | Quasi-Poisson                      | RR\                             | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
|                                              |                                    | (risques relatifs)              | avec `family = quasipoisson`        | avec `family = quasipoisson`        | avec `family = quasipoisson`                              | avec `family = quasipoisson`        |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | Binomial négatif                   | RR\                             | `MASS::glm.nb()`                    | `sjstats::svyglm.nb()`              | `lme4::glmer.nb()`                                        |                                     |
|                                              |                                    | (risques relatifs)              |                                     |                                     |                                                           |                                     |
|                                              |                                    |                                 |                                     | Alternative :\                      |                                                           |                                     |
|                                              |                                    |                                 |                                     | `svrepmisc::svynb()`                |                                                           |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
| **Incidence / Taux / Ratio**                 | Poisson\                           | IRR\                            | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
|                                              | avec *offset*                      | (*incidence rate ratio*)        | avec `family = poisson`\            | avec `family = poisson`\            | avec `family = poisson`\                                  | avec `family = poisson`\            |
|                                              |                                    |                                 | et `offset(log(denominateur))`      | et `offset(log(denominateur))`      | et `offset(log(denominateur))`                            | et `offset(log(denominateur))`      |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | Quasi-Poisson\                     | IRR\                            | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
|                                              | avec *offset*                      | (*incidence rate ratio*)        | avec `family = quasipoisson`\       | avec `family = quasipoisson`\       | avec `family = quasipoisson`\                             | avec `family = quasipoisson`\       |
|                                              |                                    |                                 | et `offset(log(denominateur))`      | et `offset(log(denominateur))`      | et `offset(log(denominateur))`                            | et `offset(log(denominateur))`      |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | Binomial négatif\                  | IRR\                            | `MASS::glm.nb()`\                   | `sjstats::svyglm.nb()`\             | `lme4::glmer.nb()`\                                       |                                     |
|                                              | avec *offset*                      | (*incidence rate ratio*)        | avec `offset(log(denominateur))`    | et `offset(log(denominateur))`      | avec `offset(log(denominateur))`                          |                                     |
|                                              |                                    |                                 |                                     |                                     |                                                           |                                     |
|                                              |                                    |                                 |                                     | Alternative :\                      |                                                           |                                     |
|                                              |                                    |                                 |                                     | `svrepmisc::svynb()`\               |                                                           |                                     |
|                                              |                                    |                                 |                                     | avec `offset(log(denominateur))`    |                                                           |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
| **Binaire**\                                 | Logistique\                        | OR\                             | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
| (oui / non)                                  | (logit)                            | (*odds ratio*)                  | avec `family = binomial`            | avec `family = binomial`            | avec `family = binomial`                                  | avec `family = binomial`            |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | Quasi-binomial\                    | OR\                             | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
|                                              | (logit)                            | (*odds ratio*)                  | avec `family = quasibinomial`       | avec `family = quasibinomial`       | avec `family = quasibinomial`                             | avec `family = quasibinomial`       |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | Probit                             | pas interprétable directement   | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
|                                              |                                    |                                 | avec `family = binomial("probit")`  | avec `family = binomial("probit")`  | avec `family = binomial("probit")`                        | avec `family = binomial("probit")`  |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | Log binomial                       | PR\                             | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
|                                              |                                    | (*prevalence ratio*)            | avec `family = binomial("log")`     | avec `family = binomial("log")`     | avec `family = binomial("log")`                           | avec `family = binomial("log")`     |
|                                              |                                    |                                 |                                     |                                     |                                                           |                                     |
|                                              |                                    |                                 | Alternative :\                      |                                     |                                                           |                                     |
|                                              |                                    |                                 | `logbin::logbin()`                  |                                     |                                                           |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | Poisson                            | PR\                             | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
|                                              |                                    | (*prevalence ratio*)            | avec `family = poisson`             | avec `family = poisson`             | avec `family = poisson`                                   | avec `family = poisson`             |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
| **Catégorielle ordinale**\                   | Régression logistique ordinale     | OR\                             | `ordinal::clm()`                    | `svrepmisc::svyclm()`               | `ordinal::clmm()`                                         | `geepack::ordgee()`                 |
| (3 modalités ou plus)                        |                                    | (*odds ratio*)                  |                                     |                                     |                                                           |                                     |
|                                              |                                    |                                 | Alternative :\                      | Alternative :\                      |                                                           | Alternative :\                      |
|                                              |                                    |                                 | `VGAM::vglm()`\                     | `svyVGAM::svy_vglm()`\              |                                                           | `multgee::ordLORgee()`              |
|                                              |                                    |                                 | avec `family = VGAM::cumulative(`\  | avec `family = VGAM::cumulative(`\  |                                                           |                                     |
|                                              |                                    |                                 |   `parallel = TRUE`\                |   `parallel = TRUE`\                |                                                           |                                     |
|                                              |                                    |                                 | `)`                                 | `)`                                 |                                                           |                                     |
|                                              |                                    |                                 |                                     |                                     |                                                           |                                     |
|                                              |                                    |                                 | Alternative :\                      | Alternative :\                      |                                                           |                                     |
|                                              |                                    |                                 | `MASS::polr()`                      | `survey::svyolr()`                  |                                                           |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
| **Catégorielle nominale\                     | Régression logistique multinomiale | OR\                             | `nnet::multinom()`                  | `svrepmisc::svymultinom()`          | Voir note [^choix-modele-2]                               | `multgee::nomLORgee()`              |
| **(3 modalités ou plus)                      |                                    | (*odds ratio*)                  |                                     |                                     |                                                           |                                     |
|                                              |                                    |                                 | Alternative :\                      | Alternative :\                      |                                                           |                                     |
|                                              |                                    |                                 | `VGAM::vglm()`\                     | `svyVGAM::svy_vglm()`\              |                                                           |                                     |
|                                              |                                    |                                 | avec `family = VGAM::multinomial`   | avec `family = VGAM::multinomial`   |                                                           |                                     |
|                                              |                                    |                                 |                                     |                                     |                                                           |                                     |
|                                              |                                    |                                 | Alternative :\                      |                                     |                                                           |                                     |
|                                              |                                    |                                 | `mlogit::mlogit()`                  |                                     |                                                           |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
| **Survie\                                    | Cox                                | HR\                             | `survival::coxph()`                 | `survey::svycoxph()`                | `survival::coxph()`\                                      | `survival::coxph()`\                |
| **(*time to event*)                          |                                    | (*hazard ratio*)                |                                     |                                     | avec un terme `survival::frailty()`                       | avec l'option `cluster`             |
|                                              |                                    |                                 |                                     |                                     |                                                           |                                     |
|                                              |                                    |                                 |                                     |                                     | Alternative :\                                            |                                     |
|                                              |                                    |                                 |                                     |                                     | `coxme::coxme()`                                          |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | Modèle à temps discret binomial\   | HR\                             | `stats::glm()`\                     | `survey::svyglm()`\                 | `lme4::glmer()`\                                          | `geepack::geeglm()`\                |
|                                              | (*cloglog*)                        | (*hazard ratio*)                | avec `family = binomial("cloglog")` | avec `family = binomial("cloglog")` | avec `family = binomial("cloglog")`                       | avec `family = binomial("cloglog")` |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | *Accelerated failure time*\        | HR\                             | `survival::survreg()`               | `survey::svysurvreg()`              | `survival::survreg()` avec un terme `survival::frailty()` | `survival::survreg()`\              |
|                                              | (AFT)                              | (*hazard ratio*)                |                                     |                                     |                                                           | avec l'option `cluster`             |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
| **Comptage avec surreprésentation de zéros** | *Zero-inflated Poisson*            | OR & RR                         | `pscl::zeroinfl()`                  | `sjstats::svyglm.zip()`             | `GLMMadaptive::mixed_model()`\                            |                                     |
|                                              |                                    |                                 |                                     |                                     | avec `family = zi.poisson()`[^choix-modele-3]             |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | *Hurdle Poisson model*             | OR & RR                         | `pscl::hurdle()`                    |                                     | `GLMMadaptive::mixed_model()`\                            |                                     |
|                                              |                                    |                                 |                                     |                                     | avec `family = hurdle.poisson()`                          |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | *Zero-inflated negative binomial*  | OR & RR                         | `pscl::zeroinfl()`\                 | `sjstats::svyglm.zip()`\            | `GLMMadaptive::mixed_model()`\                            |                                     |
|                                              |                                    |                                 | avec `dist = "negbin"`              | avec `dist = "negbin"`              | avec `family = zi.negative.binomial()`                    |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+
|                                              | *Hurdle negative binomial model*   | OR & RR                         | `pscl::hurdle()`\                   |                                     | `GLMMadaptive::mixed_model()`\                            |                                     |
|                                              |                                    |                                 | avec `dist = "negbin"`              |                                     | avec `family = hurdle.negative.binomial()`                |                                     |
+----------------------------------------------+------------------------------------+---------------------------------+-------------------------------------+-------------------------------------+-----------------------------------------------------------+-------------------------------------+

: {.stripped .sm .responsive .hover}
:::
:::

[^choix-modele-1]: Voir aussi `gee::gee()` comme alternative à `geepack::geeglm()`.

[^choix-modele-2]: Il n'y a pas de solution évidente.

    L'approche la plus simple consiste à réaliser plusieurs modèles logistiques binaires séparés à l'aide de `lme4::glmer()`. Si la variable à expliquer a trois niveaux (A, B et C), on pourra réaliser un modèle binaire B vs A, et un modèle binaire C vs A. Cette approche est appelée <q>approximation de Begg et Gray</q>. On trouvera, en anglais, plus d'explications et des références bibliographiques sur [StackOverflow](https://stackoverflow.com/a/23795087/7943547).

    Une approche alternative, dans un contexte bayésien et non fréquentiste, est d'avoir recours à `brms::brm()` qui peut gérer ce type de modèles. Cette approche, avec des exemples de code, est mentionnée sur [StackOverflow](https://stackoverflow.com/a/37892379/7943547).

    Dans le cadre d'une approche fréquentiste, la fonction `mgcv::gam()` est mentionnée sur [StackExchange](https://stats.stackexchange.com/a/555654), de même que la fonction `mixcat::npmlt()` ([voir ce post](https://stats.stackexchange.com/a/493035)), sachant que le package `{mixcat}` est faiblement documenté et ne semble plus forcément maintenu.

    Enfin, il semble possible d'avoir recours à `MCMCglmm::MCMCglmm()`, selon cette réponse sur [StackOverflow](https://stackoverflow.com/a/22027859)et ce [billet de blog](https://hlplab.wordpress.com/2009/05/07/multinomial-random-effects-models-in-r/).

[^choix-modele-3]: Cf. <https://drizopoulos.github.io/GLMMadaptive/articles/ZeroInflated_and_TwoPart_Models.html>

::: {.content-hidden unless-format="pdf"}
Ce tableau est trop grand pour un rendu au format PDF. Merci de le consulter en ligne à l'adresse <https://larmarange.github.io/guide-R/analyses_avancees/choix-modele.html>.
:::
