---
format: 
  revealjs:
    theme: moon
execute: 
  echo: true
---


```{r}
#| output-location: column
v <- c(1.2, 8.7, 5.6, 11.4)
v
```

---

```{r}
#| output-location: column
#| code-line-numbers: "3"
v <- c(1.2, 8.7, 5.6, 11.4)
v |> 
  mean()
```

---

```{r}
#| output-location: column
#| code-line-numbers: "4"
v <- c(1.2, 8.7, 5.6, 11.4)
v |> 
  mean() |> 
  round(digits = 1)
```

---


```{r}
#| output-location: column
#| code-line-numbers: "5"
v <- c(1.2, 8.7, 5.6, 11.4)
v |> 
  mean() |> 
  round(digits = 1) |> 
  format(decimal.mark = ",")
```

---


```{r}
#| output-location: column
#| code-line-numbers: "6-10"
v <- c(1.2, 8.7, 5.6, 11.4)
v |> 
  mean() |> 
  round(digits = 1) |> 
  format(decimal.mark = ",") |> 
  paste0(
    "La moyenne est de ", 
    m = _, 
    "."
  )
```

---

```{r}
#| output-location: column
#| message: true
#| code-line-numbers: "11"
v <- c(1.2, 8.7, 5.6, 11.4)
v |> 
  mean() |> 
  round(digits = 1) |> 
  format(decimal.mark = ",") |> 
  paste0(
    "La moyenne est de ", 
    m = _, 
    "."
  ) |> 
  message()
```

