---
format: 
  revealjs:
    theme: moon
    standalone: true
    embed-resources: true
    controls: true
    width: 1600
    height: 900
    
execute: 
  echo: true
---


```{r}
#| output-location: column
library(ggsurvfit)
library(survival)
km <- 
  survfit2(
    Surv(ttdeath, death) ~ stage,
    data = gtsummary::trial
  )
```

---

```{r}
#| output-location: column
ggsurvfit(km)
```

---

```{r}
#| output-location: column
#| code-line-numbers: "2"
ggsurvfit(km) +
  khroma::scale_color_bright()
```

---

```{r}
#| output-location: column
#| code-line-numbers: "3-4"
ggsurvfit(km) +
  khroma::scale_color_bright() +
  scale_x_continuous(breaks = 0:4*6) +
  scale_y_continuous(labels = scales::percent)
```

---

```{r}
#| output-location: column
#| code-line-numbers: "5-6"
ggsurvfit(km) +
  khroma::scale_color_bright() +
  scale_x_continuous(breaks = 0:4*6) +
  scale_y_continuous(labels = scales::percent) +
  xlab("Mois depuis le diagnostic") +
  ylab("Proportion toujours en vie")
```

---

```{r}
#| output-location: column
#| code-line-numbers: "7"
ggsurvfit(km) +
  khroma::scale_color_bright() +
  scale_x_continuous(breaks = 0:4*6) +
  scale_y_continuous(labels = scales::percent) +
  xlab("Mois depuis le diagnostic") +
  ylab("Proportion toujours en vie") +
  add_confidence_interval()
```

---

```{r}
#| output-location: column
#| code-line-numbers: "8"
ggsurvfit(km) +
  khroma::scale_color_bright() +
  scale_x_continuous(breaks = 0:4*6) +
  scale_y_continuous(labels = scales::percent) +
  xlab("Mois depuis le diagnostic") +
  ylab("Proportion toujours en vie") +
  add_confidence_interval() +
  khroma::scale_fill_bright()
```

---

```{r}
#| output-location: column
#| code-line-numbers: "9"
ggsurvfit(km) +
  khroma::scale_color_bright() +
  scale_x_continuous(breaks = 0:4*6) +
  scale_y_continuous(labels = scales::percent) +
  xlab("Mois depuis le diagnostic") +
  ylab("Proportion toujours en vie") +
  add_confidence_interval() +
  khroma::scale_fill_bright() +
  add_quantile(y_value = 0.5, color = "gray50")
```

---

```{r}
#| output-location: column
#| code-line-numbers: "10"
ggsurvfit(km) +
  khroma::scale_color_bright() +
  scale_x_continuous(breaks = 0:4*6) +
  scale_y_continuous(labels = scales::percent) +
  xlab("Mois depuis le diagnostic") +
  ylab("Proportion toujours en vie") +
  add_confidence_interval() +
  khroma::scale_fill_bright() +
  add_quantile(y_value = 0.5, color = "gray50") +
  add_pvalue()
```

---

```{r}
#| output-location: column
#| code-line-numbers: "11"
ggsurvfit(km) +
  khroma::scale_color_bright() +
  scale_x_continuous(breaks = 0:4*6) +
  scale_y_continuous(labels = scales::percent) +
  xlab("Mois depuis le diagnostic") +
  ylab("Proportion toujours en vie") +
  add_confidence_interval() +
  khroma::scale_fill_bright() +
  add_quantile(y_value = 0.5, color = "gray50") +
  add_pvalue() + 
  add_risktable()
```

---

```{r}
#| output-location: column
#| code-line-numbers: "12-15"
ggsurvfit(km) +
  khroma::scale_color_bright() +
  scale_x_continuous(breaks = 0:4*6) +
  scale_y_continuous(labels = scales::percent) +
  xlab("Mois depuis le diagnostic") +
  ylab("Proportion toujours en vie") +
  add_confidence_interval() +
  khroma::scale_fill_bright() +
  add_quantile(y_value = 0.5, color = "gray50") +
  add_pvalue() + 
  add_risktable(
    stats_label = list(
      "n.risk" = "Personnes à risque",
      "cum.event" = "Nombre de décès"
    )
  )
```

