# Ressources documentaires {#sec-ressources-documentaires}

Dans ce dernier chapitre, nous listons quelques ressources documentaires, notamment sur des domaines non couverts par *guide-R*.

## Ressources génériques

-   [*Introduction à R et au tidyverse*](https://juba.github.io/tidyverse/) de Julien Barnier

-   [*Awesome R*](https://github.com/qinwf/awesome-R) : cette liste recense des ressources sur différents domaines

-   [Rzine](http://rzine.fr/) : un site collaboratif et interdisciplinaire de référencement et de partage de documentation sur la pratique de **R** en sciences humaines et sociales

-   [Rseek](http://www.rseek.org/) : un moteur de recherche restreignant les résultats à un corpus de sources sur **R**

-   [*R for data science*](https://r4ds.hadley.nz/) par Hadley Wickham, Mine Çetinkaya-Rundel et Garret Grolemund

-   [*UtilitR*](https://www.utilitr.org/), une documentation sur **R** née à l'INSEE

-   [*Notes de cours de R*](https://egallic.fr/Enseignement/R/Book/) par Ewan Gallic

-   [*Programmer en R*](https://fr.wikibooks.org/wiki/Programmer_en_R), un wikibook collaboratif

-   [*Introduction à la programmation en R*](https://cran.r-project.org/doc/contrib/Goulet_introduction_programmation_R.pdf) par Vincent Goulet

-   [*Happy Git and GitHub for the useR*](https://happygitwithr.com/) par Jennifer Bryan

-   [*Modern Data Science with R*](https://mdsr-book.github.io/mdsr3e/) par Benjamin S. Baumer, Daniel T. Kaplan, and Nicholas J. Horton

-   [*The Epidemiologist R Handbook: R for applied epidemiology and public health*](https://epirhandbook.com/) porté par un collectif d'auteurs

-   [*R for Non-Programmers: A Guide for Social Scientists*](https://bookdown.org/daniel_dauber_io/r4np_book/) par Daniel Dauber

## Quarto / Rmarkdown / Rapports automatisés

-   [*Formation Quarto*](https://mthevenin.gitlab.io/support_quarto/) de Marc Thévenin

-   Chapitre <q>[Diffuser et publier avec **rmarkdown**](https://juba.github.io/tidyverse/13-rmarkdown.html)</q> dans l'*Introduction à R ey au tidyverse* de Julien Barnier

-   Documentation officielle de Quarto (en anglais) : <https://quarto.org/docs/get-started/>

-   Chapitre <q>[Quarto](https://r4ds.hadley.nz/quarto)</q> de l'ouvrage *R for Data Science* de Hadley Wickham, Mine Çetinkaya-Rundel et Garret Grolemund

-   [*De R Markdown à Quarto pour aller plus loin avec ses publications*](https://cderv.quarto.pub/tuto-quarto-rr2023/) Rencontres R 2023 à Avignon

## Analyse de réseaux

-   [*L'analyse de réseau en sciences sociales. Petit guide pratique*](https://hal.science/hal-04052709) par Laurent Beauguitte, HAL : [hal-04052709](https://hal.science/hal-04052709)

-   [*Network visualization with R*](https://kateto.net/network-visualization) par Katherine Ognyanova

-   [*Awesome Network Analysis list*](https://github.com/briatte/awesome-network-analysis) portée par François Briatte

-   [*Cours d'introduction à l'analyse de réseaux avec R*](https://huguespecout.github.io/Analyse_r-seaux_GDR_ARSHS/) par Hugues Pecout et Laurent Beauguitte

## Analyse spatiale & Cartographie

-   [*Cartographie avec R*](https://rcarto.github.io/cartographie_avec_r/) et [*Géomatique avec R*](https://rcarto.github.io/geomatique_avec_r/) par Timothée Giraud et Hugues Pecout

-   [*Données géospatiales et cartographie avec R*](https://roelandtn.frama.io/slides/2090628_meetup_Raddict_datageo.html) par Nicolas Roelandt

-   [*Économétrie spatiale : une introduction pratique*](https://www.insee.fr/fr/statistiques/2408659) par Ronan Le Saout et Jean-Michel Floch

-   [*Geocomputation with R*](https://r.geocompx.org/) par Robin Lovelace, Jakub Nowosad et Jannes Muenchow

-   [*Spatial Modelling for Data Scientists*](https://gdsl-ul.github.io/san/) par Francisco Rowe et Dani Arribas-Bel

-   [*Spatial Data Science with R and "terra"*](https://rspatial.org/index.html#) par Robert J. Hijmans

## Analyse textuelle

-   [*Le Descriptoire : Recueil et analyse de texte*](http://perso.ens-lyon.fr/lise.vaudor/Descriptoire/_book/) avec R par Lise Vaudor

-   [*Text mining with R*](https://www.tidytextmining.com/) par Julia Silge et David Robinson

-   [*Course script for SICSS Paris*](https://bookdown.org/f_lennert/sicss-bookdown/) par Julien Boelaert, Felix Lennert et Étienne Ollien pour l'école d'été 2023 du SICSS portant sur l'extraction de données textuelles à partir du web (*scraping*)
