---
format: 
  revealjs:
    theme: moon
    standalone: true
    embed-resources: true
    controls: true
    width: 1920
    height: 1080
    
execute: 
  echo: true
---

<style>
.reveal pre.sourceCode code {
  max-height: none !important;
}

</style>

---

```{r}
#| output-location: column
library(ggplot2)
ggplot(iris)
```

---

```{r}
#| output-location: column
#| code-line-numbers: "3-7"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  )
```

---

```{r}
#| output-location: column
#| code-line-numbers: "8"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point()
```

---

```{r}
#| output-location: column
#| code-line-numbers: "9-12"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale"
  )
```

---

```{r}
#| output-location: column
#| code-line-numbers: "12"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  )
```

---

```{r}
#| output-location: column
#| code-line-numbers: "14-16"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  ) +
  ggtitle(
    "Relation entre longueur et largeur des pétales"
  )
```

---

```{r}
#| output-location: column
#| code-line-numbers: "16"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  ) +
  ggtitle(
    "Relation entre longueur et largeur des pétales",
    subtitle = "Jeu de données Iris"
  )
```

---

```{r}
#| output-location: column
#| code-line-numbers: "18"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  ) +
  ggtitle(
    "Relation entre longueur et largeur des pétales",
    subtitle = "Jeu de données Iris"
  ) +
  scale_x_continuous(breaks = 1:7)
```

---

```{r}
#| output-location: column
#| code-line-numbers: "19-21"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  ) +
  ggtitle(
    "Relation entre longueur et largeur des pétales",
    subtitle = "Jeu de données Iris"
  ) +
  scale_x_continuous(breaks = 1:7) +
  scale_y_continuous(
    labels = scales::label_number(decimal.mark = ",")
  )
```

---

```{r}
#| output-location: column
#| code-line-numbers: "22"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  ) +
  ggtitle(
    "Relation entre longueur et largeur des pétales",
    subtitle = "Jeu de données Iris"
  ) +
  scale_x_continuous(breaks = 1:7) +
  scale_y_continuous(
    labels = scales::label_number(decimal.mark = ",")
  ) +
  coord_equal()
```

---

```{r}
#| output-location: column
#| code-line-numbers: "23"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  ) +
  ggtitle(
    "Relation entre longueur et largeur des pétales",
    subtitle = "Jeu de données Iris"
  ) +
  scale_x_continuous(breaks = 1:7) +
  scale_y_continuous(
    labels = scales::label_number(decimal.mark = ",")
  ) +
  coord_equal() +
  facet_grid(cols = vars(Species))
```

---

```{r}
#| output-location: column
#| code-line-numbers: "24"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  ) +
  ggtitle(
    "Relation entre longueur et largeur des pétales",
    subtitle = "Jeu de données Iris"
  ) +
  scale_x_continuous(breaks = 1:7) +
  scale_y_continuous(
    labels = scales::label_number(decimal.mark = ",")
  ) +
  coord_equal() +
  facet_grid(cols = vars(Species)) +
  guides(color = guide_legend(nrow = 2))
```

---

```{r}
#| output-location: column
#| code-line-numbers: "25"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  ) +
  ggtitle(
    "Relation entre longueur et largeur des pétales",
    subtitle = "Jeu de données Iris"
  ) +
  scale_x_continuous(breaks = 1:7) +
  scale_y_continuous(
    labels = scales::label_number(decimal.mark = ",")
  ) +
  coord_equal() +
  facet_grid(cols = vars(Species)) +
  guides(color = guide_legend(nrow = 2)) +
  theme_light()
```

---

```{r}
#| output-location: column
#| code-line-numbers: "26-28"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  ) +
  ggtitle(
    "Relation entre longueur et largeur des pétales",
    subtitle = "Jeu de données Iris"
  ) +
  scale_x_continuous(breaks = 1:7) +
  scale_y_continuous(
    labels = scales::label_number(decimal.mark = ",")
  ) +
  coord_equal() +
  facet_grid(cols = vars(Species)) +
  guides(color = guide_legend(nrow = 2)) +
  theme_light() +
  theme(
    legend.position = "bottom"
  )
```


---

```{r}
#| output-location: column
#| code-line-numbers: "28"
library(ggplot2)
ggplot(iris) +
  aes(
    x = Petal.Length, 
    y = Petal.Width, 
    colour = Species
  ) +
  geom_point() +
  labs(
    x = "Longueur du pétale",
    y = "Largeur du pétale",
    colour = "Espèce"
  ) +
  ggtitle(
    "Relation entre longueur et largeur des pétales",
    subtitle = "Jeu de données Iris"
  ) +
  scale_x_continuous(breaks = 1:7) +
  scale_y_continuous(
    labels = scales::label_number(decimal.mark = ",")
  ) +
  coord_equal() +
  facet_grid(cols = vars(Species)) +
  guides(color = guide_legend(nrow = 2)) +
  theme_light() +
  theme(
    legend.position = "bottom",
    axis.title = element_text(face = "bold")
  )
```

