---
format: 
  revealjs:
    theme: moon
    standalone: true
    embed-resources: true
    controls: true
    width: 1600
    height: 900
    
execute: 
  echo: true
---

<style>
.reveal pre.sourceCode code {
  max-height: none !important;
}

</style>

```{r}
#| message: false
#| output-location: column
library(ggplot2)
ggplot(gtsummary::trial) +
  aes(x = stage) +
  geom_bar()
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "5"
library(ggplot2)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    fill = grade 
  ) +
  geom_bar()
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "8"
library(ggplot2)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    fill = grade, 
  ) +
  geom_bar(
    position = position_dodge(.9)
  )
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "2, 6, 8, 10"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  )
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "9, 15, 16, 17, 18"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop)),
    stat = "prop"
  )
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "18"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop)),
    stat = "prop", 
    position = position_dodge(.9)
  )
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "19"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop)),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  )
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "16"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  )
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "21"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent)
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "22"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_brewer()
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "23"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_brewer() +
  theme_light()
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "24,25"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_brewer() +
  theme_light() +
  xlab("") +
  ylab("")
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "26"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_brewer() +
  theme_light() +
  xlab("") +
  ylab("") +
  labs(fill = "")
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "27"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_brewer() +
  theme_light() +
  xlab("") +
  ylab("") +
  labs(fill = "") +
  ggtitle("Distribution selon le niveau, par grade")
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "28,29,30"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_brewer() +
  theme_light() +
  xlab("") +
  ylab("") +
  labs(fill = "") +
  ggtitle("Distribution selon le niveau, par grade") +
  theme(
    legend.position = "top"
  )
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "30"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_brewer() +
  theme_light() +
  xlab("") +
  ylab("") +
  labs(fill = "") +
  ggtitle("Distribution selon le niveau, par grade") +
  theme(
    legend.position = "top",
    panel.grid = element_blank()
  )
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "31"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_brewer() +
  theme_light() +
  xlab("") +
  ylab("") +
  labs(fill = "") +
  ggtitle("Distribution selon le niveau, par grade") +
  theme(
    legend.position = "top",
    panel.grid = element_blank(),
    panel.border = element_blank()
  )
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "32"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_brewer() +
  theme_light() +
  xlab("") +
  ylab("") +
  labs(fill = "") +
  ggtitle("Distribution selon le niveau, par grade") +
  theme(
    legend.position = "top",
    panel.grid = element_blank(),
    panel.border = element_blank(),
    axis.text.y = element_blank()
  )
```

---

```{r}
#| message: false
#| output-location: column
#| code-line-numbers: "33"
library(ggplot2)
library(ggstats)
ggplot(gtsummary::trial) +
  aes(
    x = stage,
    y = after_stat(prop),
    fill = grade, 
    by = grade,
    label = scales::percent(after_stat(prop), accuracy = 1)
  ) +
  geom_bar(
    stat = "prop", 
    position = position_dodge(.9)
  ) +
  geom_text(
    aes(y = after_stat(prop) - 0.01),
    stat = "prop", 
    position = position_dodge(.9),
    vjust = "top"
  ) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_brewer() +
  theme_light() +
  xlab("") +
  ylab("") +
  labs(fill = "") +
  ggtitle("Distribution selon le niveau, par grade") +
  theme(
    legend.position = "top",
    panel.grid = element_blank(),
    panel.border = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank()
  )
```
